//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyboardSwitch.Settings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyboardSwitch.Settings.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        internal static string AddKeyFormat {
            get {
                return ResourceManager.GetString("AddKeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        internal static string AppTheme {
            get {
                return ResourceManager.GetString("AppTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fluent.
        /// </summary>
        internal static string AppThemeFluent {
            get {
                return ResourceManager.GetString("AppThemeFluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to macOS.
        /// </summary>
        internal static string AppThemeMacOS {
            get {
                return ResourceManager.GetString("AppThemeMacOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string AppThemeSimple {
            get {
                return ResourceManager.GetString("AppThemeSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant.
        /// </summary>
        internal static string AppThemeVariant {
            get {
                return ResourceManager.GetString("AppThemeVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string AppThemeVariantAuto {
            get {
                return ResourceManager.GetString("AppThemeVariantAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string AppThemeVariantDark {
            get {
                return ResourceManager.GetString("AppThemeVariantDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string AppThemeVariantLight {
            get {
                return ResourceManager.GetString("AppThemeVariantLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-configure.
        /// </summary>
        internal static string AutoConfigure {
            get {
                return ResourceManager.GetString("AutoConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward.
        /// </summary>
        internal static string Backward {
            get {
                return ResourceManager.GetString("Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward key is invalid.
        /// </summary>
        internal static string BackwardInvalid {
            get {
                return ResourceManager.GetString("BackwardInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward key is required.
        /// </summary>
        internal static string BackwardRequired {
            get {
                return ResourceManager.GetString("BackwardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        internal static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Mappings.
        /// </summary>
        internal static string CharMapping {
            get {
                return ResourceManager.GetString("CharMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate characters are not allowed: {0}.
        /// </summary>
        internal static string CharsDuplicatedFormat {
            get {
                return ResourceManager.GetString("CharsDuplicatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by Tolik Pylypchuk.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current position: {0}.
        /// </summary>
        internal static string CurrentPositionFormat {
            get {
                return ResourceManager.GetString("CurrentPositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete layout configuration.
        /// </summary>
        internal static string DeleteLayoutConfiguration {
            get {
                return ResourceManager.GetString("DeleteLayoutConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward key is invalid.
        /// </summary>
        internal static string ForwardInvalid {
            get {
                return ResourceManager.GetString("ForwardInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward key is required.
        /// </summary>
        internal static string ForwardRequired {
            get {
                return ResourceManager.GetString("ForwardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get new version.
        /// </summary>
        internal static string GetNewVersion {
            get {
                return ResourceManager.GetString("GetNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t forget to stop the Keyboard Switch service before installing the new version.
        /// </summary>
        internal static string GetNewVersionHint {
            get {
                return ResourceManager.GetString("GetNewVersionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant switching.
        /// </summary>
        internal static string InstantSwitching {
            get {
                return ResourceManager.GetString("InstantSwitching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Switch.
        /// </summary>
        internal static string KeyboardSwitch {
            get {
                return ResourceManager.GetString("KeyboardSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Keyboard Switch service is not running.
        /// </summary>
        internal static string KeyboardSwitchServiceNotRunning {
            get {
                return ResourceManager.GetString("KeyboardSwitchServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Keyboard Switch service is running.
        /// </summary>
        internal static string KeyboardSwitchServiceRunning {
            get {
                return ResourceManager.GetString("KeyboardSwitchServiceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Keyboard Switch service is shutting down.
        /// </summary>
        internal static string KeyboardSwitchServiceShuttingDown {
            get {
                return ResourceManager.GetString("KeyboardSwitchServiceShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key combinations to switch layouts:.
        /// </summary>
        internal static string KeysToSwitchLayouts {
            get {
                return ResourceManager.GetString("KeysToSwitchLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key combinations to switch text:.
        /// </summary>
        internal static string KeysToSwitchText {
            get {
                return ResourceManager.GetString("KeysToSwitchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        internal static string Kill {
            get {
                return ResourceManager.GetString("Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No keys for switching layouts backward specified.
        /// </summary>
        internal static string LayoutBackwardKeysEmpty {
            get {
                return ResourceManager.GetString("LayoutBackwardKeysEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No keys for switching layouts forward specified.
        /// </summary>
        internal static string LayoutForwardKeysEmpty {
            get {
                return ResourceManager.GetString("LayoutForwardKeysEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys for switching layouts are same.
        /// </summary>
        internal static string LayoutKeysAreSame {
            get {
                return ResourceManager.GetString("LayoutKeysAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Alt.
        /// </summary>
        internal static string ModifierKeyAlt {
            get {
                return ResourceManager.GetString("ModifierKeyAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Command.
        /// </summary>
        internal static string ModifierKeyCommand {
            get {
                return ResourceManager.GetString("ModifierKeyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Ctrl.
        /// </summary>
        internal static string ModifierKeyCtrl {
            get {
                return ResourceManager.GetString("ModifierKeyCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Alt.
        /// </summary>
        internal static string ModifierKeyLeftAlt {
            get {
                return ResourceManager.GetString("ModifierKeyLeftAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Command.
        /// </summary>
        internal static string ModifierKeyLeftCommand {
            get {
                return ResourceManager.GetString("ModifierKeyLeftCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ctrl.
        /// </summary>
        internal static string ModifierKeyLeftCtrl {
            get {
                return ResourceManager.GetString("ModifierKeyLeftCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Option.
        /// </summary>
        internal static string ModifierKeyLeftOption {
            get {
                return ResourceManager.GetString("ModifierKeyLeftOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Shift.
        /// </summary>
        internal static string ModifierKeyLeftShift {
            get {
                return ResourceManager.GetString("ModifierKeyLeftShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Super.
        /// </summary>
        internal static string ModifierKeyLeftSuper {
            get {
                return ResourceManager.GetString("ModifierKeyLeftSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Win.
        /// </summary>
        internal static string ModifierKeyLeftWin {
            get {
                return ResourceManager.GetString("ModifierKeyLeftWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;no key&gt;.
        /// </summary>
        internal static string ModifierKeyNone {
            get {
                return ResourceManager.GetString("ModifierKeyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Option.
        /// </summary>
        internal static string ModifierKeyOption {
            get {
                return ResourceManager.GetString("ModifierKeyOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Alt.
        /// </summary>
        internal static string ModifierKeyRightAlt {
            get {
                return ResourceManager.GetString("ModifierKeyRightAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Command.
        /// </summary>
        internal static string ModifierKeyRightCommand {
            get {
                return ResourceManager.GetString("ModifierKeyRightCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Ctrl.
        /// </summary>
        internal static string ModifierKeyRightCtrl {
            get {
                return ResourceManager.GetString("ModifierKeyRightCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Option.
        /// </summary>
        internal static string ModifierKeyRightOption {
            get {
                return ResourceManager.GetString("ModifierKeyRightOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Shift.
        /// </summary>
        internal static string ModifierKeyRightShift {
            get {
                return ResourceManager.GetString("ModifierKeyRightShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Super.
        /// </summary>
        internal static string ModifierKeyRightSuper {
            get {
                return ResourceManager.GetString("ModifierKeyRightSuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Win.
        /// </summary>
        internal static string ModifierKeyRightWin {
            get {
                return ResourceManager.GetString("ModifierKeyRightWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier keys must be different in each row.
        /// </summary>
        internal static string ModifierKeysAreSame {
            get {
                return ResourceManager.GetString("ModifierKeysAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string ModifierKeySeparator {
            get {
                return ResourceManager.GetString("ModifierKeySeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Shift.
        /// </summary>
        internal static string ModifierKeyShift {
            get {
                return ResourceManager.GetString("ModifierKeyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Super.
        /// </summary>
        internal static string ModifierKeySuper {
            get {
                return ResourceManager.GetString("ModifierKeySuper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Win.
        /// </summary>
        internal static string ModifierKeyWin {
            get {
                return ResourceManager.GetString("ModifierKeyWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        internal static string Modifiers {
            get {
                return ResourceManager.GetString("Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you have installed one or more new layouts. You should configure and save them.
        /// </summary>
        internal static string NewLayoutsHint {
            get {
                return ResourceManager.GetString("NewLayoutsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version available: {0}.
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version!.
        /// </summary>
        internal static string NoNewVersions {
            get {
                return ResourceManager.GetString("NoNewVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you input the number then press &apos;Enter&apos; to apply changes.
        /// </summary>
        internal static string NumberBoxHint {
            get {
                return ResourceManager.GetString("NumberBoxHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press count.
        /// </summary>
        internal static string PressCount {
            get {
                return ResourceManager.GetString("PressCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press count should be between 1 and 10.
        /// </summary>
        internal static string PressCountInvalid {
            get {
                return ResourceManager.GetString("PressCountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that you have uninstalled one or more layouts. You can delete their configuration from the app&apos;s settings.
        /// </summary>
        internal static string RemoveLayoutsHint {
            get {
                return ResourceManager.GetString("RemoveLayoutsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox.
        /// </summary>
        internal static string Sandbox {
            get {
                return ResourceManager.GetString("Sandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox is a where you can test out your changes in settings and preferences.
        /// </summary>
        internal static string SandboxInfo {
            get {
                return ResourceManager.GetString("SandboxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a message about uninstalled layouts.
        /// </summary>
        internal static string ShowUninstalledLayoutsMessage {
            get {
                return ResourceManager.GetString("ShowUninstalledLayoutsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the service when you log in.
        /// </summary>
        internal static string StartOnLogIn {
            get {
                return ResourceManager.GetString("StartOnLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch layouts.
        /// </summary>
        internal static string SwitchLayouts {
            get {
                return ResourceManager.GetString("SwitchLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods of forward and backward switching must be different.
        /// </summary>
        internal static string SwitchMethodsAreSame {
            get {
                return ResourceManager.GetString("SwitchMethodsAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch settings:.
        /// </summary>
        internal static string SwitchSettings {
            get {
                return ResourceManager.GetString("SwitchSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme will be updated after application restart.
        /// </summary>
        internal static string UpdateThemeHint {
            get {
                return ResourceManager.GetString("UpdateThemeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use xsel for clipboard integration.
        /// </summary>
        internal static string UseXsel {
            get {
                return ResourceManager.GetString("UseXsel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try this option if the clipboard handling doesn&apos;t work well for you. xsel must be installed manually for this option to work. Keyboard Switch must be restarted if this setting is changed..
        /// </summary>
        internal static string UseXselHint {
            get {
                return ResourceManager.GetString("UseXselHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string ValidationNameEmpty {
            get {
                return ResourceManager.GetString("ValidationNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string VersionFormat {
            get {
                return ResourceManager.GetString("VersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View the docs.
        /// </summary>
        internal static string ViewDocs {
            get {
                return ResourceManager.GetString("ViewDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait time (ms).
        /// </summary>
        internal static string WaitMilliseconds {
            get {
                return ResourceManager.GetString("WaitMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait time should be between 100 and 1000 milliseconds.
        /// </summary>
        internal static string WaitMillisecondsInvalid {
            get {
                return ResourceManager.GetString("WaitMillisecondsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Switch Settings.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
