<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="System.Interactive" />
    <PackageReference Include="System.Interactive.Async" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KeyboardSwitch.Core\KeyboardSwitch.Core.csproj" />
    <ProjectReference Include="..\KeyboardSwitch.Windows\KeyboardSwitch.Windows.csproj" Condition="$(TargetOS) == 'Windows'" />
    <ProjectReference Include="..\KeyboardSwitch.MacOS\KeyboardSwitch.MacOS.csproj" Condition="$(TargetOS) == 'macOS'" />
    <ProjectReference Include="..\KeyboardSwitch.Linux\KeyboardSwitch.Linux.csproj" Condition="$(TargetOS) == 'Linux'" />
  </ItemGroup>
</Project>
