<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="DynamicData" Version="9.4.33" />
    <PackageReference Include="ReactiveUI" Version="23.2.28" />
    <PackageReference Include="ReactiveUI.Validation" Version="7.1.0" />
    <PackageReference Include="Splat" Version="19.4.1" />
    <PackageReference Include="System.Interactive" Version="7.0.1" />
    <PackageReference Include="System.Interactive.Async" Version="7.0.1" />
    <PackageReference Include="System.Reactive" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KeyboardSwitch.Core\KeyboardSwitch.Core.csproj" />
  </ItemGroup>
</Project>
