<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="DynamicData" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="ReactiveUI.Validation" />
    <PackageReference Include="Splat" />
    <PackageReference Include="System.Interactive" />
    <PackageReference Include="System.Interactive.Async" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KeyboardSwitch.Core\KeyboardSwitch.Core.csproj" />
  </ItemGroup>
</Project>
