<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsAotCompatible>false</IsAotCompatible>
    <TrimMode>partial</TrimMode>
    <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DynamicData" />
    <PackageReference Include="ReactiveUI.Reactive" />
    <PackageReference Include="ReactiveUI.Validation.Reactive" />
    <PackageReference Include="Splat" />
    <PackageReference Include="System.Interactive" />
    <PackageReference Include="System.Interactive.Async" />
    <PackageReference Include="System.Reactive" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KeyboardSwitch.Core\KeyboardSwitch.Core.csproj" />
  </ItemGroup>
</Project>
