<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.Sinks.Async" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.Debug" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="SharpHook" />
    <PackageReference Include="SharpHook.Reactive" />
    <PackageReference Include="System.Interactive" />
    <PackageReference Include="System.Interactive.Async" />
    <PackageReference Include="System.Reactive" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Extensions" />
    <PackageReference Include="TestableIO.System.IO.Abstractions.Wrappers" />
  </ItemGroup>
</Project>
