//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyboardSwitch.Settings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyboardSwitch.Settings.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add custom layout.
        /// </summary>
        internal static string AddCustomLayout {
            get {
                return ResourceManager.GetString("AddCustomLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward.
        /// </summary>
        internal static string Backward {
            get {
                return ResourceManager.GetString("Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward key is invalid.
        /// </summary>
        internal static string BackwardInvalid {
            get {
                return ResourceManager.GetString("BackwardInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward key is required.
        /// </summary>
        internal static string BackwardRequired {
            get {
                return ResourceManager.GetString("BackwardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        internal static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Mappings.
        /// </summary>
        internal static string CharMapping {
            get {
                return ResourceManager.GetString("CharMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate characters are not allowed: {0}.
        /// </summary>
        internal static string CharsDuplicatedFormat {
            get {
                return ResourceManager.GetString("CharsDuplicatedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert.
        /// </summary>
        internal static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter.
        /// </summary>
        internal static string Converter {
            get {
                return ResourceManager.GetString("Converter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter lets you map characters between custom layouts that are independent from those defined in your system.
        /// </summary>
        internal static string ConverterInfo {
            get {
                return ResourceManager.GetString("ConverterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Converter Settings.
        /// </summary>
        internal static string ConverterSettings {
            get {
                return ResourceManager.GetString("ConverterSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The converter requires at least 2 cusom layouts.
        /// </summary>
        internal static string ConverterTooFewCustomLayouts {
            get {
                return ResourceManager.GetString("ConverterTooFewCustomLayouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or press Ctrl+Enter.
        /// </summary>
        internal static string ConvertInfo {
            get {
                return ResourceManager.GetString("ConvertInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layouts must be different.
        /// </summary>
        internal static string CustomLayoutsAreSame {
            get {
                return ResourceManager.GetString("CustomLayoutsAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward key is invalid.
        /// </summary>
        internal static string ForwardInvalid {
            get {
                return ResourceManager.GetString("ForwardInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward key is required.
        /// </summary>
        internal static string ForwardRequired {
            get {
                return ResourceManager.GetString("ForwardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot key.
        /// </summary>
        internal static string HotKey {
            get {
                return ResourceManager.GetString("HotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instant switching.
        /// </summary>
        internal static string InstantSwitching {
            get {
                return ResourceManager.GetString("InstantSwitching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Keyboard Switch service is not running.
        /// </summary>
        internal static string KeyboardSwitchServiceNotRunning {
            get {
                return ResourceManager.GetString("KeyboardSwitchServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Keyboard Switch service is running.
        /// </summary>
        internal static string KeyboardSwitchServiceRunning {
            get {
                return ResourceManager.GetString("KeyboardSwitchServiceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Keyboard Switch service is shutting down.
        /// </summary>
        internal static string KeyboardSwitchServiceShuttingDown {
            get {
                return ResourceManager.GetString("KeyboardSwitchServiceShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        internal static string Kill {
            get {
                return ResourceManager.GetString("Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        internal static string ModifierKeyAlt {
            get {
                return ResourceManager.GetString("ModifierKeyAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        internal static string ModifierKeyCtrl {
            get {
                return ResourceManager.GetString("ModifierKeyCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ModifierKeyNone {
            get {
                return ResourceManager.GetString("ModifierKeyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier keys.
        /// </summary>
        internal static string ModifierKeys {
            get {
                return ResourceManager.GetString("ModifierKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string ModifierKeyShift {
            get {
                return ResourceManager.GetString("ModifierKeyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string ModifierKeysSeparator {
            get {
                return ResourceManager.GetString("ModifierKeysSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        internal static string ModifierKeyWin {
            get {
                return ResourceManager.GetString("ModifierKeyWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers.
        /// </summary>
        internal static string Modifiers {
            get {
                return ResourceManager.GetString("Modifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string NameEmpty {
            get {
                return ResourceManager.GetString("NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press count.
        /// </summary>
        internal static string PressCount {
            get {
                return ResourceManager.GetString("PressCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press count should be between 1 and 10.
        /// </summary>
        internal static string PressCountInvalid {
            get {
                return ResourceManager.GetString("PressCountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox.
        /// </summary>
        internal static string Sandbox {
            get {
                return ResourceManager.GetString("Sandbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sandbox is a where you can test out your changes in settings and preferences.
        /// </summary>
        internal static string SandboxInfo {
            get {
                return ResourceManager.GetString("SandboxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source text.
        /// </summary>
        internal static string SourceText {
            get {
                return ResourceManager.GetString("SourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap.
        /// </summary>
        internal static string Swap {
            get {
                return ResourceManager.GetString("Swap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch layout.
        /// </summary>
        internal static string SwitchLayout {
            get {
                return ResourceManager.GetString("SwitchLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methods of forward and backward switching must be different.
        /// </summary>
        internal static string SwitchMethodsAreSame {
            get {
                return ResourceManager.GetString("SwitchMethodsAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch mode.
        /// </summary>
        internal static string SwitchMode {
            get {
                return ResourceManager.GetString("SwitchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target text.
        /// </summary>
        internal static string TargetText {
            get {
                return ResourceManager.GetString("TargetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string ValidationNameEmpty {
            get {
                return ResourceManager.GetString("ValidationNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait time (ms).
        /// </summary>
        internal static string WaitMilliseconds {
            get {
                return ResourceManager.GetString("WaitMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait time should be between 100 and 1000 milliseconds.
        /// </summary>
        internal static string WaitMillisecondsInvalid {
            get {
                return ResourceManager.GetString("WaitMillisecondsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Switch Settings.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
