//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeyboardSwitch.Settings.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeyboardSwitch.Settings.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward.
        /// </summary>
        internal static string Backward {
            get {
                return ResourceManager.GetString("Backward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backward key is required.
        /// </summary>
        internal static string BackwardRequired {
            get {
                return ResourceManager.GetString("BackwardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character Mappings.
        /// </summary>
        internal static string CharMapping {
            get {
                return ResourceManager.GetString("CharMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward.
        /// </summary>
        internal static string Forward {
            get {
                return ResourceManager.GetString("Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forward key is required.
        /// </summary>
        internal static string ForwardRequired {
            get {
                return ResourceManager.GetString("ForwardRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Keyboard Switch service is not running.
        /// </summary>
        internal static string KeyboardSwitchServiceNotRunning {
            get {
                return ResourceManager.GetString("KeyboardSwitchServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Keyboard Switch service is running.
        /// </summary>
        internal static string KeyboardSwitchServiceRunning {
            get {
                return ResourceManager.GetString("KeyboardSwitchServiceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Keyboard Switch service is shutting down.
        /// </summary>
        internal static string KeyboardSwitchServiceShuttingDown {
            get {
                return ResourceManager.GetString("KeyboardSwitchServiceShuttingDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill.
        /// </summary>
        internal static string Kill {
            get {
                return ResourceManager.GetString("Kill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        internal static string ModifierKeyAlt {
            get {
                return ResourceManager.GetString("ModifierKeyAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        internal static string ModifierKeyCtrl {
            get {
                return ResourceManager.GetString("ModifierKeyCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ModifierKeyNone {
            get {
                return ResourceManager.GetString("ModifierKeyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier key combinations for forward and backward switching must be different.
        /// </summary>
        internal static string ModifierKeysAreSame {
            get {
                return ResourceManager.GetString("ModifierKeysAreSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string ModifierKeyShift {
            get {
                return ResourceManager.GetString("ModifierKeyShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string ModifierKeysSeparator {
            get {
                return ResourceManager.GetString("ModifierKeysSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Win.
        /// </summary>
        internal static string ModifierKeyWin {
            get {
                return ResourceManager.GetString("ModifierKeyWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot key.
        /// </summary>
        internal static string PreferencesHotKey {
            get {
                return ResourceManager.GetString("PreferencesHotKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier keys.
        /// </summary>
        internal static string PreferencesModifierKeys {
            get {
                return ResourceManager.GetString("PreferencesModifierKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press count.
        /// </summary>
        internal static string PressCount {
            get {
                return ResourceManager.GetString("PressCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press count should be between 1 and 10.
        /// </summary>
        internal static string PressCountInvalid {
            get {
                return ResourceManager.GetString("PressCountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press cound is required.
        /// </summary>
        internal static string PressCountRequired {
            get {
                return ResourceManager.GetString("PressCountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch mode.
        /// </summary>
        internal static string SwitchMode {
            get {
                return ResourceManager.GetString("SwitchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait time (ms).
        /// </summary>
        internal static string WaitMilliseconds {
            get {
                return ResourceManager.GetString("WaitMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait time should be between 100 and 1000 milliseconds.
        /// </summary>
        internal static string WaitMillisecondsInvalid {
            get {
                return ResourceManager.GetString("WaitMillisecondsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait time is required.
        /// </summary>
        internal static string WaitMillisecondsRequired {
            get {
                return ResourceManager.GetString("WaitMillisecondsRequired", resourceCulture);
            }
        }
    }
}
