name: Build and deploy the docs to GitHub Pages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Jekyll Actions
      uses: helaili/jekyll-action@master
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}
